version: '3.1'
services:
  elasticsearch1:
    image: elasticsearch:5.6.11
    container_name: elasticsearch1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ems_node1:/usr/share/elasticsearch/data
      - ./docker/elasticsearch/node1.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200

  elasticsearch2:
    image: elasticsearch:5.6.11
    container_name: elasticsearch2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ems_node2:/usr/share/elasticsearch/data
      - ./docker/elasticsearch/node2.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    image: kibana:5.6
    container_name: ems-kibana
    volumes:
      - ./docker/elasticsearch/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
    - 5601:5601

  tika:
    image: logicalspark/docker-tikaserver
    container_name: ems-tika
    ports:
    - 9998:9998

  web:
    image: nginx:alpine
    container_name: ems-webserver
    working_dir: /application
    volumes:
    - ./src:/application
    - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "1090:80"

  ems:
    build: docker/php-fpm
    container_name: ems
    working_dir: /application
    volumes:
    - ./src:/application
    - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

  db:
    image: postgres:9.6-alpine
    container_name: ems-db
    working_dir: /application
    volumes:
    - ems_db:/var/lib/postgresql/data
    - .:/application
    ports:
    - "5433:5432"
    environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DB=ems

volumes:
  ems_node1:
    driver: local
  ems_node2:
    driver: local
  ems_db:
    driver: local
